name: "Generate Documentation"

on:
  workflow_run:
    workflows: [ "Core Continuous Integration (CI)" ]
    types: [ completed ]
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
      - name: "Generate App Token"
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: "Generate Docs"
        uses: vargiuscuola/genshdoc@v1

      - name: "Commit & Push Changes"
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "docs: update automated documentation [skip ci]"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          file_pattern: 'README.md'
          token: ${{ steps.app-token.outputs.token }}